Revert "Tradefed: Generate more descriptive test names"
This reverts commit 209ec20c3fee871452be9d66fcb042d8d1be5bf7.

Reason for revert: Breaks individual run-test:
```
$ ./art/test/run-test --host 023-many-interfaces
/ssd2/android/standalone_internal2/art/test/023-many-interfaces: Create runner script...
Traceback (most recent call last):
  File "/ssd2/android/standalone_internal2/./art/test/run-test", line 895, in <module>
    runner = create_runner_script()
  File "/ssd2/android/standalone_internal2/./art/test/run-test", line 857, in create_runner_script
    ctx.export(FULL_TEST_NAME=os.environ['FULL_TEST_NAME'])
                              ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 717, in __getitem__
KeyError: 'FULL_TEST_NAME'
```

Bug: 147812905
Change-Id: Iab4147ff76afdf4fb91e0c7b158694af1cf1433b