Fix -Wnontrivial-memcall warning
Memcall functions work at the byte level so they don't know about C++
semantics and these C++ objects might not have trivial
constructors or destructors. I silenced the warning by explicitly
casting the pointer to void* with static_cast. I did this fix because I
assume the code developer knows the consequences with using memcall
functions with C++ objects.

art/runtime/subtype_check.h:456:14: error: first argument in call to
'memcpy' is a pointer to non-trivially copyable type
'SubtypeCheckBitsAndStatus' [-Werror,-Wnontrivial-memcall]
  456 |       memcpy(&tmp, &int32_data, sizeof(tmp));
      |              ^

art/libartbase/base/arena_containers.h:263:14: error: first argument in
call to 'memset' is a pointer to non-trivially copyable type
'art::verifier::RegisterLine' [-Werror,-Wnontrivial-memcall]
  263 |       memset(ptr, kMagicFill, size);
      |              ^

Flag: EXEMPT warning bugfix
Bug: 430598176
Test: m && presubmits
Change-Id: I59ba9fc74e1694420d78a3393b493c782bc08f50